# Generated by Django 5.0 on 2023-12-20 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile/')),
                ('coverImg', models.ImageField(default='cover.png', upload_to='profile_cover/')),
                ('relationship', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('Others', 'Other')], max_length=150)),
                ('phone', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Others', 'Others')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
