# Generated by Django 5.0 on 2023-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendlyApp', '0002_alter_profile_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
